name: CI pipeline
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Установка зависимостей
        run: npm ci

      - name: Линтинг
        run: npm run lint

      - name: Запуск тестов
        run: npm run test

      - name: Логин в Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Сборка Docker-образа
        run: docker build -t ${{ secrets.DOCKER_USER }}/my-node-app:${{ github.sha }} .

      - name: Публикация Docker-образа
        run: docker push ${{ secrets.DOCKER_USER }}/my-node-app:${{ github.sha }}
